pages:
  stage: deploy
  script:
    - echo "Copying files to public directory..."
    - mkdir public
    - cp -r index.html style.css src public
  artifacts:
    paths:
      - public
  only:
    - main
