image: node:latest

pages:
  stage: deploy
  script:
    - echo "Installing dependencies..."
    - npm install
    - echo "Building the project..."
    - npm run build
    - echo "Deploying..."
  artifacts:
    paths:
      - public
  tags:
    - Pages
  only:
    - main
    - seths_branch
