pages:
  stage: deploy
  script:
    - mkdir public
    - cp -r src/data public/data
    - cp index.html public
    - cp style.css public
    - cp main.js public
  artifacts:
    paths:
      - public
  only:
    - main
